#!/bin/bash --login

cd "$(dirname "$0")"
TARGET_FILE="$(basename "$0")"
while [ -L "$TARGET_FILE" ]; do
    TARGET_FILE="$(readlink "$TARGET_FILE")"
    cd "$(dirname "$TARGET_FILE")"
    TARGET_FILE="$(basename "$TARGET_FILE")"
done
mono decentralized-yggdrasil.exe askpass
